char * clone(char * s);
void inspect(char * s, int len);
int length(char * s);
int rawLength(char * s);
char * reverse(char * s);
char * convertString(char * s, int offset);
void ascii();
char * toLower(char * s);
char * toUpper(char * s);
char * clone(char * s);
int stringEquals(char * s1, char * s2);
int stringEqualsNoCase(char * s1, char * s2);
char * stringConcat(char * s1, char * s2);
void echoStrings(char * s);
char ** split(char * s, char delimiter);
